### ISSUE TITLE
Doesn't do UDP

### ISSUE THREAD

**Issue by jimmbelll** [shinnok/netcatgui#4]
Hey! Love the concept for this tool.  But I wish it did UDP like nc.  Cheers!

**Comment by shinnok** [comment]
Hi @jimmbelll,

Thanks for the feedback. Yes, UDP is on the [TODO](https://github.com/shinnok/netcatgui/blob/master/TODO) list. Hopefully I'll get some time soon to overhaul NetcatGUI and implement some of the pending features. :-)
